all: format setPort
setPort:
	sudo chmod 777 /dev/ttyACM0
format:
	./format.sh
help:
	@echo Please make sure that you run these code files with Arduino IDE.
	@echo This makefile would not execute them.
